language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
install: npm install
script:
- npm test
- grunt dist
- grunt codedeploy
deploy:
- provider: s3
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: Piet2/bPZA6fbQ2HRlocKxKCbwkaCKJkm1xUm5XLC/xQ5+MsQ3nOSVYwxFlswlH/CBh4m7xZ+NcOGsq+XqwpCVX9MPsYLck+mtEFTRsUMsxw692o4UU9FDJw9bq7a4hBvz5wcl15RdsJsY0euLBBL4aFZoc7T+Eu2SoQQVRj1kg=
  skip_cleanup: true
  bucket: hmda-edit-check-api
  local_dir: dist
  upload-dir: develop
  on:
    all_branches: true
- provider: codedeploy
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: Piet2/bPZA6fbQ2HRlocKxKCbwkaCKJkm1xUm5XLC/xQ5+MsQ3nOSVYwxFlswlH/CBh4m7xZ+NcOGsq+XqwpCVX9MPsYLck+mtEFTRsUMsxw692o4UU9FDJw9bq7a4hBvz5wcl15RdsJsY0euLBBL4aFZoc7T+Eu2SoQQVRj1kg=
  bucket: hmda-edit-check-api
  key: develop/hmda-edit-check-api-codedeploy.zip
  application: hmda-edit-check-api
  deployment_group: hmda-edit-check-api-dev
  on:
    all_branches: true
- provider: s3
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: Piet2/bPZA6fbQ2HRlocKxKCbwkaCKJkm1xUm5XLC/xQ5+MsQ3nOSVYwxFlswlH/CBh4m7xZ+NcOGsq+XqwpCVX9MPsYLck+mtEFTRsUMsxw692o4UU9FDJw9bq7a4hBvz5wcl15RdsJsY0euLBBL4aFZoc7T+Eu2SoQQVRj1kg=
  skip_cleanup: true
  bucket: hmda-edit-check-api
  local_dir: dist
  upload-dir: master
  on:
    branch: master
- provider: codedeploy
  access_key_id: AKIAIMTOX4BXGVFOB56Q
  secret_access_key:
    secure: Piet2/bPZA6fbQ2HRlocKxKCbwkaCKJkm1xUm5XLC/xQ5+MsQ3nOSVYwxFlswlH/CBh4m7xZ+NcOGsq+XqwpCVX9MPsYLck+mtEFTRsUMsxw692o4UU9FDJw9bq7a4hBvz5wcl15RdsJsY0euLBBL4aFZoc7T+Eu2SoQQVRj1kg=
  bucket: hmda-edit-check-api
  key: master/hmda-edit-check-api-codedeploy.zip
  application: hmda-edit-check-api
  deployment_group: hmda-edit-check-api-prod
  on:
    branch: master
notifications:
  hipchat:
    rooms:
      secure: T0cvwtL8w6ZaRbYl80IN4I1a5AtKauhwuSPTWEoPNZhcWnG1DYLH0Txjg5x9iTbncctx0QoeQad5EYrfoCCqkSarGJR/j9u29Lnla647BCjTSnpbMjVe3vqw+brNF0Vw68W6eTwBhiCUagwZWJxCLpMnTx9MVD/JuR6VWHqLSQI=
